In [221]:
import kaggle
import pandas as pd
!kaggle competitions download -c mercedes-benz-greener-manufacturing

mercedes-benz-greener-manufacturing.zip: Skipping, found more recently modified local copy (use --force to force download)


In [222]:
import os
from zipfile import ZipFile
file = os.listdir()
if "data" in file:
    for i in file:
        if i.endswith(".zip"):
            file_path = os.getcwd()+"/"+i
            ZipFile(file_path).extractall(os.getcwd()+"/data")
            break
else:
    for i in file:
        if i.endswith(".zip"):
            os.makedirs(os.getcwd()+"/data")
            file_path = os.getcwd()+"/"+i
            ZipFile(file_path).extractall(os.getcwd()+"/data")
            break



In [223]:
path_ = os.chdir(os.getcwd())
path_
file_1 = os.listdir()
for i in file_1:
    if i.endswith(".zip"):
        file_path_1 = os.getcwd()+"/"+i
        ZipFile(file_path_1).extractall()


In [224]:
import pandas as pd
def fetch_data():
    train_data = pd.read_csv("D:\my work\kaggle\Mercedes_Benz\data\\train.csv")
    test_data = pd.read_csv("D:\my work\kaggle\Mercedes_Benz\data\\test.csv")
    samp_sub_data = pd.read_csv("D:\my work\kaggle\Mercedes_Benz\data\sample_submission.csv")
    return train_data, test_data, samp_sub_data

In [225]:
train_data, test_data, sample_submission_data = fetch_data()

In [226]:
train_data.shape


(4209, 378)

In [227]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [228]:
train_data.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [229]:
train_data.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [230]:
# getting the null values
train_data.isnull().sum()
#there are no null values as of now

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [231]:
train = train_data.copy()

In [232]:
# categorical and numerical values
train.drop("ID", axis=1, inplace=True)
cat_var = [x for x in train.columns if train[x].dtype == 'O']
num_var = [x for x in train.columns if train[x].dtype != 'O' and x!='y']


In [233]:
cat_var


['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

In [234]:
corr_matrix = train.corr()


In [235]:
for i in num_var:
    print("{}---->\n{}".format(i, corr_matrix[i]))

X10---->
y      -0.026985
X10     1.000000
X11          NaN
X12    -0.033084
X13    -0.028806
          ...   
X380   -0.010479
X382   -0.010164
X383   -0.004740
X384   -0.002532
X385   -0.004387
Name: X10, Length: 369, dtype: float64
X11---->
y      NaN
X10    NaN
X11    NaN
X12    NaN
X13    NaN
        ..
X380   NaN
X382   NaN
X383   NaN
X384   NaN
X385   NaN
Name: X11, Length: 369, dtype: float64
X12---->
y       0.089792
X10    -0.033084
X11          NaN
X12     1.000000
X13     0.214825
          ...   
X380   -0.005566
X382   -0.024937
X383   -0.011628
X384   -0.006212
X385   -0.010765
Name: X12, Length: 369, dtype: float64
X13---->
y       0.048276
X10    -0.028806
X11          NaN
X12     0.214825
X13     1.000000
          ...   
X380    0.023045
X382   -0.021713
X383   -0.010125
X384    0.041242
X385   -0.009373
Name: X13, Length: 369, dtype: float64
X14---->
y       0.193643
X10    -0.100474
X11          NaN
X12    -0.246513
X13    -0.083141
          ...   
X380    0.00774

In [236]:
# here accoridng to the dataset and the corr matrix X11 should be droped from the dataset as it has no impact on the target variable
train.drop("X11", axis=1, inplace=True)

In [237]:
for i in num_var:
    print()


In [238]:
max_ = float(max(train["X13"]))
max_

1.0

In [239]:
train.head()


y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   
3   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0   
4   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 376 columns]

In [240]:
#encoding categorical variable
train["X1"].unique
# so i have to use one hot encoding for it

<bound method Series.unique of 0       v
1       t
2       w
3       t
4       v
       ..
4204    s
4205    o
4206    v
4207    r
4208    r
Name: X1, Length: 4209, dtype: object>

In [241]:
y = train["y"]
train.drop("y", axis=1, inplace=True)
X = train

In [242]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [243]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoding', OneHotEncoder(handle_unknown = 'ignore'), cat_var)], remainder='passthrough')
X = ct.fit_transform(X)

In [244]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(X,y)

RandomForestRegressor()

In [245]:
y_train_pred = forest_reg.predict(X)

In [246]:
y_train_pred, y

(array([121.52815   ,  90.3848    ,  76.67490333, ..., 110.05987   ,
         90.2723    , 104.2135    ]),
 0       130.81
 1        88.53
 2        76.26
 3        80.62
 4        78.02
          ...  
 4204    107.39
 4205    108.77
 4206    109.22
 4207     87.48
 4208    110.85
 Name: y, Length: 4209, dtype: float64)

In [247]:
import numpy as np
from sklearn.metrics import mean_squared_error
score = mean_squared_error(y_train_pred, y)
rmse = np.sqrt(score)
rmse

3.7821790306329914

In [248]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(forest_reg, X, y, cv=3)
scores


array([0.47407591, 0.54948343, 0.57356575])

In [249]:
from sklearn.model_selection import cross_val_predict
scores_predict = cross_val_predict(forest_reg, X, y, cv=3)
scores_predict

array([101.85187833,  94.76528333,  77.0926    , ..., 110.3036    ,
        95.32374119,  93.51775   ])

In [250]:
X_test = test_data
X_test.drop(["ID", "X11"], axis=1, inplace=True)

In [251]:
X_test = ct.transform(X_test)

In [252]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [253]:
y_test = sample_submission_data
y_test.drop("ID", axis=1, inplace=True)
y_test


y
0     100.669318
1     100.669318
2     100.669318
3     100.669318
4     100.669318
...          ...
4204  100.669318
4205  100.669318
4206  100.669318
4207  100.669318
4208  100.669318

[4209 rows x 1 columns]

In [263]:
import matplotlib.pyplot as plt
def plottin_curve(model, X_train, y_train, X_test, y_test):
    train_errors, val_errors = [], []
    for m in range(1, len(X_train)):
        model.fit(X_train[:m], y_train[:m])
        y_train_pred = model.predict(X_train[:m])
        y_val_predict = model.predict(X_test)
        train_errors.append(mean_squared_error(y_train, y_train_pred))
        val_errors.append(mean_squared_error(y_test, y_val_predict))
    plt.plot(np.sqrt(train_errors), "r+", linewidth=2, label="train")
    plt.plot(np.sqrt(val_errors), "g+", linewidth=2, label="test")

forest_reg_1 = RandomForestRegressor()
plottin_curve(forest_reg_1, X, y, X_test, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [4209, 1]

In [255]:
y_test_pred = forest_reg.predict(X_test)


In [256]:
test_data['X2'].unique()

array(['n', 'ai', 'as', 'ae', 's', 'b', 'e', 'ak', 'm', 'a', 'aq', 'ag',
       'r', 'k', 'aj', 'ay', 'ao', 'an', 'ac', 'af', 'ax', 'h', 'i', 'f',
       'ap', 'p', 'au', 't', 'z', 'y', 'aw', 'd', 'at', 'g', 'am', 'j',
       'x', 'ab', 'w', 'q', 'ah', 'ad', 'al', 'av', 'u'], dtype=object)

In [257]:
train_data['X2'].unique()

array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
       'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
       'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
       'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object)

In [258]:
type(X_test)

numpy.ndarray

In [260]:
y_test_pred

array([ 76.73865333, 110.84195   ,  76.97947833, ...,  93.888575  ,
       107.94205   ,  91.31303   ])

In [270]:
submission = pd.DataFrame(y_test_pred, columns=["y"])
submission.to_csv('sub.csv')

In [271]:
submission_ = pd.read_csv('sub.csv')
submission_


Unnamed: 0           y
0              0   76.738653
1              1  110.841950
2              2   76.979478
3              3   77.440700
4              4  110.748550
...          ...         ...
4204        4204  102.326586
4205        4205   94.800540
4206        4206   93.888575
4207        4207  107.942050
4208        4208   91.313030

[4209 rows x 2 columns]

In [273]:
submission_.drop(columns="Unnamed: 0", axis=1, inplace=True)


In [274]:
submission_


y
0      76.738653
1     110.841950
2      76.979478
3      77.440700
4     110.748550
...          ...
4204  102.326586
4205   94.800540
4206   93.888575
4207  107.942050
4208   91.313030

[4209 rows x 1 columns]

In [275]:
submission_["ID"] = [i for i in range(1, 8517)]


ValueError: Length of values (8516) does not match length of index (4209)